version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    container_name: halfagiraf_traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--api.dashboard=false"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/dynamic.yml"
      - "--providers.docker.network=web"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "444:443"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic.yml:/dynamic.yml:ro
    networks:
      - web

  remix:
    build: .
    container_name: halfagiraf_remix_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # Primary router for halfagiraf.com
      - "traefik.http.routers.remix.rule=Host(`halfagiraf.com`)"
      - "traefik.http.routers.remix.entrypoints=web"
      - "traefik.http.routers.remix.tls=true"
      - "traefik.http.services.remix.loadbalancer.server.port=3000"
      # Additional router for www.halfagiraf.com (301 redirect)
      - "traefik.http.routers.remix-www.rule=Host(`www.halfagiraf.com`)"
      - "traefik.http.routers.remix-www.entrypoints=web"
      - "traefik.http.routers.remix-www.middlewares=redirect-to-nonwww"
      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.regex=^https?://www\\.halfagiraf\\.com(.*)"
      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.replacement=https://halfagiraf.com$1"
      - "traefik.http.middlewares.redirect-to-nonwww.redirectregex.permanent=true"
    networks:
      - web

  db:
    image: postgres:15-alpine
    container_name: halfagiraf_pg_db
    restart: always
    environment:
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: halfagiraf_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - web
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mydbuser -d halfagiraf_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: halfagiraf_pg_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.halfagiraf.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
    networks:
      - web

  nominatim:
    image: mediagis/nominatim:4.5
    container_name: halfagiraf_nominatim
    restart: always
    environment:
      # Use the United Kingdom extract (1.8 GB)
      PBF_URL: "https://download.geofabrik.de/europe/united-kingdom-latest.osm.pbf"
      REPLICATION_URL: "https://download.geofabrik.de/europe/united-kingdom-updates/"
      NOMINATIM_PASSWORD: "very_secure_password"
      IMPORT_WIKIPEDIA: "false"
    ports:
      - "8081:8080" # Expose Nominatim on port 8081
    volumes:
      - nominatim-data:/var/lib/postgresql/16/main
      - nominatim-flatnode:/nominatim/flatnode
    networks:
      - web

networks:
  web:
    external: true

volumes:
  pg_data:
  pgadmin_data:
  nominatim-data:
  nominatim-flatnode:
